### ISSUE TITLE
Error when removing migration ("relational store [..] without either DbConnection or connection string")

### ISSUE THREAD

**Issue by ocinf** [iammukeshm/multitenancy-aspnet-core#1]
Hi,

Thanks for this project! Unfortunately I'm having difficulties when trying to remove a migration. Running the project and adding migrations works without problems, executing "remove-migration" results in the following error message:

```
PM> Remove-Migration
Build started...
Build succeeded.
System.InvalidOperationException: A relational store has been configured without specifying either the DbConnection or connection string to use.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.RemoveMigration(String projectDir, String rootNamespace, Boolean force, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigrationImpl(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
**A relational store has been configured without specifying either the DbConnection or connection string to use.**
```

Steps to reproduce:
1. Clone repo
2. Execute project, post some new records to the "Products"-endpoint
3. Add simple property to Product entity (like 'public string Something { get; set; }')
4. add-migration "test"
5. run
6. remove-migration => error message

Do you know how to solve this issue?

**Comment by ocinf** [comment]
Ok, nevermind. 
I just realized that this probably will never work, as the ApplicationDbContext can't be created correctly by the migration commandlets - connection strings to the tenant data bases just aren't accessible. 
So, if you're following this approach (which still is very interesting), you need to manually delete redundant migrations. The same error happens with 'update-database', so applying migrations indeed needs to be done by the application at runtime (which is implemented in this demo project) or by creating SQL scripts by executing 'script-migration' and executing these manually.

Still leaning EF core and migrations in particular, so please excuse my ignorance.
